description: |
  This command build application.

parameters:
  npm_token:
    type: string
    default: ""
  image_name:
    type: string
    default: ""
  image_tag:
    type: string
    default: ${CIRCLE_SHA1}
  ecr_url:
    type: string
    default: 958549588201.dkr.ecr.us-east-1.amazonaws.com

steps:
  - checkout
  - run:
      name: Define application version
      command: |
        echo "Define application version"
  - setup_remote_docker:
      docker_layer_caching: false
  - node/install:
      install-yarn: false
      node-version: '18.16'
  - npm-config/set-registry:
      registry-prurl: //npm.pkg.github.com
      scope: '@darwin-seguros'
      auth-token: << parameters.npm_token >>
  - run:
      name: Build Docker image
      environment:
        BUILD_IMAGE_IMAGE_NAME: << parameters.image_name >>
        BUILD_IMAGE_IMAGE_TAG: << parameters.image_tag >>
      command: << include(scripts/build_image.sh) >>
  - aws-cli/setup
  - run:
      name: Upload image to ECR
      environment:
        BUILD_IMAGE_ECR_URL: << parameters.ecr_url >>
        BUILD_IMAGE_IMAGE_NAME: << parameters.image_name >>
        BUILD_IMAGE_IMAGE_TAG: << parameters.image_tag >>
      command: << include(scripts/upload_image.sh) >>
